trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

variables:
  jobuuid: $(Build.BuildId)$(Agent.Id)
  build: $(Build.BuildId)
  ref: $(Build.SourceBranch)
  commit: $(Build.SourceVersion)
  branch: $(Build.SourceBranchName)
  isTaggedCommit: 'no'
  version:

jobs:
- job: DevicePlane
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:

  - script: |
      VERS=$(branch)-$(echo $(commit) | cut -c1-10)
      if [[ $(ref) == refs/tags* ]]; then
        VERS=$(echo $(ref) | sed "s|refs/tags/v||g")
        echo "##vso[task.setvariable variable=isTaggedCommit]yes"
      fi
      echo "##vso[task.setvariable variable=version]$VERS"
      echo "Version: $VERS"
    displayName: 'Set variables'

  - task: Docker@2
    displayName: 'Build develop'
    inputs:
      command: 'build'
      Dockerfile: './dockerfiles/controller-with-db/Dockerfile'
      buildContext: './'
      repository: gcr.io/focal-freedom-236620/deviceplane
      arguments: --build-arg version=$(version)
      tags: |
        $(version)
        latest

  - task: Docker@2
    displayName: 'Push develop'
    inputs:
      containerRegistry: 'Edgeworx GCP'
      repository: focal-freedom-236620/deviceplane
      command: 'push'
      Dockerfile: './dockerfiles/controller-with-db/Dockerfile'
      buildContext: './'
      tags: |
        $(version)
        latest

  - task: Docker@2
    condition: eq(variables.isTaggedCommit, 'yes')
    displayName: 'Build release'
    inputs:
      command: 'build'
      Dockerfile: './dockerfiles/controller-with-db/Dockerfile'
      buildContext: './'
      repository: docker.io/edgeworx/deviceplane
      arguments: --build-arg version=$(version)
      tags: |
        $(version)
        latest

  - task: Docker@2
    condition: eq(variables.isTaggedCommit, 'yes')
    displayName: 'Push release'
    inputs:
      containerRegistry: Edgeworx-Dockerhub
      repository: edgeworx/deviceplane
      command: 'push'
      Dockerfile: './dockerfiles/controller-with-db/Dockerfile'
      buildContext: './'
      tags: |
        $(version)
        latest
