name: CI
on:
  push:
    branches: [master, develop]
    tags: [v*]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [master, develop]

env:
  IMAGE_NAME: deviceplane-controller

jobs:
  build-publish:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Detect Environment
        uses: edgeworx/detect-environment-action@master
        id: env

      - name: Build and Publish Artifacts
        uses: edgeworx/build-push-ghcr-action@master
        with:
          build-args: |
            version=${{ github.ref_name }}
          image-name: ${{ env.IMAGE_NAME }}
          push-image: ${{ github.event_name != 'pull_request' }}
